pipeline {
    agent any

      tools {
        jdk 'java11'
      }

    triggers{
        githubPush()
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building in ...'
                echo pwd()
                sh './gradlew clean build'
            }
        }
    }
}
