pipeline {
    agent any

      tools {
        jdk 'java11'
      }

    triggers{
        githubPush()
    }

    stages {
        stage('Build') {
            steps {
                sh './gradlew clean build'
            }
        }
        stage('Send email') {
                emailext body: 'Test Message',
                    subject: 'Test Subject',
                    to: '6666350@gmail.com'
            }
    }


}
