pipeline {
    agent any

      tools {
        jdk 'java11'
      }

    triggers{
        githubPush()
    }

    stages {
        stage('Build') {
            steps {
                sh './gradlew clean build'
            }
        }
    }

    post {
        failure {
            emailext body: 'Test Message',
                     subject: 'Test Subject',
                     to: '6666350@gmail.com'
        }
        unstable {
            emailext body: 'Test Message',
                     subject: 'Test Subject',
                     to: '6666350@gmail.com'
        }
    }
}
